package org.wsk.autoTestMock.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.wsk.autoTestMock.entity.UTest;
import org.wsk.autoTestMock.entity.UTestExample;

public interface UTestMapper {
	
	UTest selectOneUser(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    long countByExample(UTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    int deleteByExample(UTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    int insert(UTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    int insertSelective(UTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    List<UTest> selectByExample(UTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") UTest record, @Param("example") UTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_test
     *
     * @mbg.generated Tue Mar 12 23:27:30 CST 2019
     */
    int updateByExample(@Param("record") UTest record, @Param("example") UTestExample example);
}